--
-- Inizializzazione dello schema per il gioco FantaMatte
--
DROP FUNCTION get_leaderboard();
DROP TABLE public.mission_proofs;
DROP TABLE public.missions;
-- 1. Tabella per le missioni
CREATE TABLE IF NOT EXISTS public.missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  mission_number INT UNIQUE,
  description TEXT,
  points INT NOT NULL DEFAULT 50,
  repeat_bonus_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Abilita l'accesso in lettura (RLS) per tutti
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Missions are viewable by everyone."
ON public.missions FOR SELECT
USING (true);


-- 2. Tabella per le prove e le missioni completate
CREATE TABLE IF NOT EXISTS public.mission_proofs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_username TEXT NOT NULL,
  mission_id BIGINT REFERENCES public.missions(id),
  points_awarded INT NOT NULL,
  proof_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- Abilita l'accesso in lettura e inserimento (RLS) per tutti
ALTER TABLE public.mission_proofs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Proofs are viewable by everyone."
ON public.mission_proofs FOR SELECT
USING (true);

CREATE POLICY "Anyone can upload a proof."
ON public.mission_proofs FOR INSERT
WITH CHECK (true);


-- 3. Funzione RPC per calcolare la classifica
CREATE OR REPLACE FUNCTION public.get_leaderboard()
RETURNS TABLE(username TEXT, total_score BIGINT, has_completed_epic BOOLEAN)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    mp.player_username,
    SUM(mp.points_awarded)::BIGINT AS total_score,
    EXISTS (
      SELECT 1 FROM public.mission_proofs WHERE player_username = mp.player_username AND mission_id = 0
    ) AS has_completed_epic
  FROM
    public.mission_proofs mp
  GROUP BY mp.player_username
  ORDER BY total_score DESC;
END;
$$;

-- 4. Funzione e Trigger per ricalcolare mission_number
CREATE OR REPLACE FUNCTION public.recalculate_mission_numbers()
RETURNS TRIGGER AS $$
BEGIN
    -- Temporarily nullify mission numbers to avoid unique constraint violations during update
    UPDATE public.missions SET mission_number = NULL;

    WITH numbered_missions AS (
        SELECT
            id,
            ROW_NUMBER() OVER (ORDER BY points ASC, id ASC) AS new_mission_number
        FROM
            public.missions
    )
    UPDATE
        public.missions m
    SET
        mission_number = nm.new_mission_number
    FROM
        numbered_missions nm
    WHERE
        m.id = nm.id;

    RETURN NULL; -- for AFTER trigger
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_recalculate_mission_numbers
AFTER INSERT OR DELETE OR UPDATE OF points ON public.missions
FOR EACH STATEMENT
EXECUTE FUNCTION public.recalculate_mission_numbers();

-- Svuota la tabella per evitare ID e mission_number duplicati
TRUNCATE TABLE public.missions RESTART IDENTITY CASCADE;

-- Inserisce le missioni con un mission_number esplicito e ordinato per punti
INSERT INTO public.missions (title, points) VALUES
('Repeat “She sells seashells by the seashore”', 5),
('Have a taste of some random food', 5),
('Have a sip of superalcohol', 10),
('Scream “CEEOOOHH”', 10),
('Tell a joke', 10),
('Ask someone else the time', 10),
('Dance', 15),
('Make a cocktail for another person', 15),
('Swap a piece of clothing', 15),
('Make the noises of an animal', 15),
('Take a picture of other people (could be you and the witness, with or without Matte)', 15),
('Say his complete name aloud', 15),
('Drink something red', 15),
('Help you find a lost item (be creative, example, “I lost my precious! Help me find it, let''s look from the tree”)', 20),
('Make a toast', 20),
('Recite a poem', 20),
('Call someone else''s parent', 20),
('Say a proverb in french', 20),
('Hide somewhere in a funny way', 20),
('Sing a song', 25),
('Convince someone to dance', 25),
('Imitate a famous person', 25),
('Start talking in rhymes', 25),
('Tell a joke to the crowd at the microphone', 25),
('Count aloud to X (you get X/2 points)', 25),
('Speak with an accent (English, Russian, German, whatever)', 25),
('Start a “CEEOOOHH” collective chant', 30),
('Give a speech', 30),
('Text an old teacher', 30),
('Do a magic trick', 30),
('Win table tennis', 30),
('Make a motivational speech to someone else (eg, “oh Matte, Pippo is sad, can you go talk to him and tell him that everything will be ok?”)', 30),
('Convince someone to sing a song', 35),
('Have someone else make a toast', 40),
('Eat something spicy', 40),
('Call a restaurant and ask if it is possible to reserve for 100 people; close the call immediately after asking the question.', 50),
('Climb a tree', 50),
('Play poker', 50),
('Lose table tennis', 50),
('Have someone else give a speech', 60);
