--
-- Inizializzazione dello schema per il gioco FantaMatte
--

-- 1. Tabella per le missioni
CREATE TABLE public.missions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  points INT NOT NULL DEFAULT 50,
  repeat_bonus_enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Abilita l'accesso in lettura (RLS) per tutti
ALTER TABLE public.missions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Missions are viewable by everyone."
ON public.missions FOR SELECT
USING (true);


-- 2. Tabella per le prove e le missioni completate
CREATE TABLE public.mission_proofs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_username TEXT NOT NULL,
  mission_id BIGINT REFERENCES public.missions(id),
  points_awarded INT NOT NULL,
  proof_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Abilita l'accesso in lettura e inserimento (RLS) per tutti
ALTER TABLE public.mission_proofs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Proofs are viewable by everyone."
ON public.mission_proofs FOR SELECT
USING (true);

CREATE POLICY "Anyone can upload a proof."
ON public.mission_proofs FOR INSERT
WITH CHECK (true);


-- 3. Funzione RPC per calcolare la classifica
CREATE OR REPLACE FUNCTION public.get_leaderboard()
RETURNS TABLE(username TEXT, total_score BIGINT, has_completed_epic BOOLEAN)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    mp.player_username,
    SUM(mp.points_awarded)::BIGINT AS total_score,
    EXISTS (
      SELECT 1 FROM public.mission_proofs WHERE player_username = mp.player_username AND mission_id = 0
    ) AS has_completed_epic
  FROM
    public.mission_proofs mp
  GROUP BY mp.player_username
  ORDER BY total_score DESC;
END;
$$;