create extension if not exists pgcrypto;
create extension if not exists citext;

create table if not exists public.guest_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  is_default boolean not null default false,
  sort_order integer not null default 100,
  members_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.event_registrations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  surname text not null,
  full_name text not null,
  username text not null unique,
  guests_count integer not null default 1 check (guests_count between 1 and 10),
  notes text,
  group_id uuid not null references public.guest_groups(id) on delete restrict,
  will_be_there boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  stay_dates text,
  host_dates text,
  hosted_by_friend boolean default false
);

create table if not exists public.music_profiles (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  full_name text not null,
  instruments text[] not null default '{}',
  genres text[] not null default '{}',
  collaboration_modes text[] not null default '{}',
  availability_notes text,
  performance_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint music_profiles_instruments_not_empty check (cardinality(instruments) > 0),
  constraint music_profiles_genres_not_empty check (cardinality(genres) > 0)
);

alter table public.music_profiles
  add column if not exists username text not null default '';

alter table public.music_profiles
  add column if not exists full_name text not null default '';

alter table public.music_profiles
  drop column if exists registration_id;

create table if not exists public.lista_invitati (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name character varying null,
  surname character varying null,
  has_registered boolean null default false,
  number_of_guests bigint null default '0'::bigint,
  is_invited boolean null default false,
  will_be_there boolean null default false,
  group_slug text null,
  registration_id uuid null references public.event_registrations(id) on delete set null,
  full_name text null,
  constraint lista_invitati_pkey primary key (id)
);

create index if not exists event_registrations_group_id_idx
  on public.event_registrations(group_id);

create index if not exists music_profiles_updated_at_idx
  on public.music_profiles(updated_at desc);

create index if not exists lista_invitati_group_slug_idx on public.lista_invitati using btree (group_slug);
create index if not exists lista_invitati_has_registered_idx on public.lista_invitati using btree (has_registered);
create index if not exists lista_invitati_full_name_idx on public.lista_invitati using btree (full_name);

create or replace function update_lista_invitati_on_registration()
returns trigger as $$
declare
  v_group_slug text;
begin
  update public.lista_invitati
  set
    has_registered = true,
    number_of_guests = new.guests_count,
    will_be_there = new.will_be_there,
    registration_id = new.id,
    name = coalesce(nullif(new.name, ''), name),
    surname = coalesce(nullif(new.surname, ''), surname),
    full_name = coalesce(nullif(new.full_name, ''), full_name)
  where full_name = new.full_name;

  if not found then
    select slug
    into v_group_slug
    from public.guest_groups
    where id = new.group_id
    limit 1;

    insert into public.lista_invitati (
      name,
      surname,
      full_name,
      has_registered,
      number_of_guests,
      is_invited,
      group_slug,
      will_be_there,
      registration_id
    )
    values (
      new.name,
      new.surname,
      new.full_name,
      true,
      new.guests_count,
      false,
      v_group_slug,
      new.will_be_there,
      new.id
    );
  end if;

  return new;
end;
$$ language plpgsql;

drop trigger if exists trigger_update_lista_invitati on public.event_registrations;
create trigger trigger_update_lista_invitati
  after insert or update on public.event_registrations
  for each row execute function update_lista_invitati_on_registration();

create or replace function public.sync_guest_group_members_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    update public.guest_groups gg
    set members_count = (
      select coalesce(sum(er.guests_count), 0)
      from public.event_registrations er
      where er.group_id = old.group_id
      and er.will_be_there = true
    )
    where gg.id = old.group_id;
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    update public.guest_groups gg
    set members_count = (
      select coalesce(sum(er.guests_count), 0)
      from public.event_registrations er
      where er.group_id = new.group_id
      and er.will_be_there = true
    )
    where gg.id = new.group_id;
  end if;

  return null;
end;
$$;

drop trigger if exists trigger_sync_guest_group_members_count
on public.event_registrations;

create trigger trigger_sync_guest_group_members_count
after insert or update or delete
on public.event_registrations
for each row
execute function public.sync_guest_group_members_count();

drop function if exists public.register_guest(text,text,text,integer,text,text,text,boolean);
create or replace function public.register_guest(
  p_name text,
  p_surname text,
  p_username text,
  p_guests_count integer default 1,
  p_notes text default null,
  p_group_slug text default 'default',
  p_new_group_name text default null,
  p_will_be_there boolean default false,
  p_stay_dates text default null,
  p_host_dates text default null,
  p_hosted_by_friend boolean default false
)
returns table (
  registration_id uuid,
  registration_username text,
  group_slug text,
  group_name text,
  saved_mode text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_group_id uuid;
  v_group_slug text;
  v_group_name text;
  v_username text;
  v_full_name text;
  v_registration_id uuid;
  v_registration_exists boolean;
begin
  if nullif(trim(coalesce(p_name, '')), '') is null then
    raise exception 'Name is required';
  end if;

  if nullif(trim(coalesce(p_surname, '')), '') is null then
    raise exception 'Surname is required';
  end if;

  if nullif(trim(coalesce(p_username, '')), '') is null then
    raise exception 'Username is required';
  end if;

  if coalesce(p_guests_count, 0) < 1 then
    raise exception 'Guests count must be at least 1';
  end if;

  v_username := lower(trim(p_username));
  v_full_name := trim(concat_ws(' ', trim(p_name), trim(p_surname)));

  if nullif(trim(coalesce(p_new_group_name, '')), '') is not null then
    v_group_name := trim(p_new_group_name);
    v_group_slug := trim(both '-' from regexp_replace(lower(v_group_name), '[^a-z0-9]+', '-', 'g'));

    if v_group_slug = '' then
      raise exception 'New group name is not valid';
    end if;

    insert into public.guest_groups (name, slug, is_default, sort_order)
    values (v_group_name, v_group_slug, false, 999)
    on conflict (slug) do nothing
    returning id, slug, name
    into v_group_id, v_group_slug, v_group_name;

    if v_group_id is null then
      select id, slug, name
      into v_group_id, v_group_slug, v_group_name
      from public.guest_groups
      where slug = v_group_slug
      limit 1;
    end if;
  else
    select id, slug, name
    into v_group_id, v_group_slug, v_group_name
    from public.guest_groups
    where slug = coalesce(nullif(trim(p_group_slug), ''), 'default')
    limit 1;

    if v_group_id is null then
      select id, slug, name
      into v_group_id, v_group_slug, v_group_name
      from public.guest_groups
      where slug = 'default'
      limit 1;
    end if;
  end if;

  if v_group_id is null then
    raise exception 'No valid group found. Seed the default groups first.';
  end if;

  select exists (
    select 1
    from public.event_registrations as er
    where er.username = v_username
  ) into v_registration_exists;

  insert into public.event_registrations (
    name,
    surname,
    full_name,
    username,
    guests_count,
    notes,
    group_id,
    will_be_there,
    stay_dates,
    host_dates,
    hosted_by_friend
  )
  values (
    trim(p_name),
    trim(p_surname),
    v_full_name,
    v_username,
    p_guests_count,
    nullif(trim(coalesce(p_notes, '')), ''),
    v_group_id,
    p_will_be_there,
    nullif(trim(coalesce(p_stay_dates, '')), ''),
    nullif(trim(coalesce(p_host_dates, '')), ''),
    p_hosted_by_friend
  )
  on conflict (username) do update
  set
    name = excluded.name,
    surname = excluded.surname,
    full_name = excluded.full_name,
    guests_count = excluded.guests_count,
    notes = excluded.notes,
    group_id = excluded.group_id,
    will_be_there = excluded.will_be_there,
    stay_dates = excluded.stay_dates,
    host_dates = excluded.host_dates,
    hosted_by_friend = excluded.hosted_by_friend,
    updated_at = timezone('utc', now())
  returning id
  into v_registration_id;

  return query
  select
    v_registration_id,
    v_username,
    v_group_slug,
    v_group_name,
    case when v_registration_exists then 'updated' else 'created' end;
end;
$$;

drop function if exists public.save_music_profile(
  text,
  text,
  text,
  text[],
  text[],
  text[],
  text,
  text
);
create or replace function public.save_music_profile(
  p_name text,
  p_surname text,
  p_username text,
  p_instruments text[] default '{}'::text[],
  p_genres text[] default '{}'::text[],
  p_collaboration_modes text[] default '{}'::text[],
  p_availability_notes text default null,
  p_performance_notes text default null
)
returns table (
  music_profile_id uuid,
  full_name text,
  saved_mode text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_username citext;
  v_full_name text;
  v_profile_id uuid;
  v_profile_exists boolean;
begin
  if nullif(trim(coalesce(p_name, '')), '') is null then
    raise exception 'Name is required';
  end if;

  if nullif(trim(coalesce(p_surname, '')), '') is null then
    raise exception 'Surname is required';
  end if;

  if nullif(trim(coalesce(p_username, '')), '') is null then
    raise exception 'username is required';
  end if;

  if coalesce(cardinality(p_instruments), 0) = 0 then
    raise exception 'At least one instrument is required';
  end if;

  if coalesce(cardinality(p_genres), 0) = 0 then
    raise exception 'At least one genre is required';
  end if;

  v_username := lower(trim(p_username))::citext;
  v_full_name := trim(concat_ws(' ', trim(p_name), trim(p_surname)));

  select exists (
    select 1
    from public.music_profiles as mp
    where mp.username = v_username
  ) into v_profile_exists;

  insert into public.music_profiles (
    username,
    full_name,
    instruments,
    genres,
    collaboration_modes,
    availability_notes,
    performance_notes
  )
  values (
    v_username,
    v_full_name,
    p_instruments,
    p_genres,
    coalesce(p_collaboration_modes, '{}'::text[]),
    nullif(trim(coalesce(p_availability_notes, '')), ''),
    nullif(trim(coalesce(p_performance_notes, '')), '')
  )
  on conflict (username) do update
  set
    full_name = excluded.full_name,
    instruments = excluded.instruments,
    genres = excluded.genres,
    collaboration_modes = excluded.collaboration_modes,
    availability_notes = excluded.availability_notes,
    performance_notes = excluded.performance_notes,
    updated_at = timezone('utc', now())
  returning id
  into v_profile_id;

  return query
  select
    v_profile_id,
    v_full_name,
    case when v_profile_exists then 'updated' else 'created' end;
end;
$$;

drop function if exists public.list_music_profiles();
create or replace function public.list_music_profiles()
returns table (
  music_profile_id uuid,
  full_name text,
  instruments text[],
  genres text[],
  collaboration_modes text[],
  availability_notes text,
  performance_notes text,
  updated_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    mp.id,
    mp.full_name,
    mp.instruments,
    mp.genres,
    mp.collaboration_modes,
    mp.availability_notes,
    mp.performance_notes,
    mp.updated_at
  from public.music_profiles as mp
  order by mp.full_name asc;
$$;

grant usage on schema public to anon, authenticated;
grant select on public.guest_groups to anon, authenticated;
grant execute on function public.register_guest(text, text, text, integer, text, text, text, boolean)
  to anon, authenticated;
grant execute on function public.save_music_profile(
  text,
  text,
  text,
  text[],
  text[],
  text[],
  text,
  text
)
  to anon, authenticated;
grant execute on function public.list_music_profiles()
  to anon, authenticated;

alter policy "groups_visual"
on "public"."guest_groups"
to anon
using (
  true
);

-- Enable RLS on sensitive tables to prevent direct SELECT access
alter table public.event_registrations enable row level security;
alter table public.music_profiles enable row level security;
alter table public.lista_invitati enable row level security;

create policy "block_select_on_event_registrations"
  on public.event_registrations
  for select
  to anon, authenticated
  using (false);

create policy "block_select_on_music_profiles"
  on public.music_profiles
  for select
  to anon, authenticated
  using (false);

create policy "block_select_on_lista_invitati"
  on public.lista_invitati
  for select
  to anon, authenticated
  using (false);